namespace MonitorErpMcp.Catalog.Content.Purchase
{
    // The using-static sits inside the namespace so the imported Content(...) builder binds before
    // the enclosing MonitorErpMcp.Catalog.Content namespace in simple-name lookup.
    using static MonitorErpMcp.Catalog.Content.ContentEntryFactory;
    using MonitorErpMcp.Catalog.Model;

    /// <summary>
    /// Hand-authored content for Purchase command records: bilingual descriptions and search aliases
    /// (en first, zh second), keyed by clrType and merged onto the structural catalog. Important
    /// request-input fields (mandatory, mandatoryWhen, enum, reference, input wrapper, nested
    /// command, dto) carry bilingual descriptions; self-evident fields are skipped.
    /// </summary>
    public static class Commands
    {
        /// <summary>Hand-authored entries for this family, merged by <c>clrType</c> onto the structural catalog.</summary>
        public static readonly ContentEntry[] Entries =
        [
            // ---- ArrivalReporting ----------------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.ArrivalReporting.ReportArrival",
                "Report the arrival of goods on purchase-order rows.",
                "上报采购订单行的货物到货。",
                ["report arrival", "arrival reporting", "report arrival of goods"], ["上报到货", "到货上报", "收货上报"],
                fields: [
                    F("Rows", "The arrival rows to report.", "要上报的到货行。"),
                    F("DeliveryNoteNumber", "The delivery-note number; required when system settings demand it.", "交货单号；系统设置要求时必填。"),
                    F("WaybillNumber", "The waybill number; required when system settings demand it.", "运单号；系统设置要求时必填。"),
                    F("ReportingEmployeeId", "The employee making the reporting; defaults to the session user's employee.", "进行上报的员工；默认为当前用户的员工。"),
                ]),

            // ---- BlanketOrderPurchases -----------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.BlanketOrderPurchases.AddBlanketOrderPurchaseRow",
                "Add a row to a blanket purchase order.",
                "为采购框架协议添加行。",
                ["add blanket row", "add blanket order row"], ["添加框架协议行", "添加协议行"],
                fields: [
                    F("BlanketOrderId", "The blanket order to add the row to.", "要添加行的采购框架协议。"),
                    F("PartId", "The part of the row.", "行的物料。"),
                    F("OrderRowType", "The type of the row (part, additional, sum, free text).", "行的类型（物料、附加、合计、自由文本）。"),
                    F("OrderedQuantity", "The ordered quantity of the row.", "行的订购数量。"),
                    F("InsertRowAfterId", "The row to insert the new row after.", "在其后插入新行的行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.BlanketOrderPurchases.CreateBlanketOrderPurchase",
                "Create a blanket purchase order.",
                "创建采购框架协议。",
                ["create blanket order", "create frame agreement"], ["创建采购框架协议", "新建框架协议"],
                fields: [
                    F("SupplierId", "The supplier of the blanket order.", "协议的供应商。"),
                    F("OrderTypeId", "The blanket-order type; defaults to the last used type.", "协议类型；默认为上次使用的类型。"),
                    F("Rows", "The rows of the blanket order.", "协议的行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.BlanketOrderPurchases.RemoveBlanketOrderPurchaseRow",
                "Remove a row from a blanket purchase order.",
                "从采购框架协议移除行。",
                ["remove blanket row", "remove order row"], ["移除框架协议行", "删除协议行"],
                fields: [
                    F("BlanketOrderRowId", "The blanket-order row to remove.", "要移除的框架协议行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.BlanketOrderPurchases.UpdateBlanketOrderPurchaseRow",
                "Update a blanket purchase-order row.",
                "更新采购框架协议行。",
                ["update blanket row", "update order row"], ["更新框架协议行"],
                fields: [
                    F("BlanketOrderRowId", "The blanket-order row to update.", "要更新的框架协议行。"),
                    F("VatRateId", "The VAT rate of the row.", "行的增值税率。"),
                ]),

            // ---- FormReports ---------------------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.FormReports.CreateInquiry",
                "Create the form report of an inquiry.",
                "创建询价单的表单报告。",
                ["create inquiry form", "create form report"], ["创建询价单表单", "生成询价单"],
                fields: [
                    F("InquiryId", "The inquiry to create the form report for.", "要创建表单报告的询价单。"),
                    F("FormReportConfigurationId", "The form-report configuration; defaults to the system's.", "表单报告配置；默认使用系统配置。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.FormReports.CreatePurchaseOrder",
                "Create the form report of a purchase order.",
                "创建采购订单的表单报告。",
                ["create purchase order form", "create order form"], ["创建采购订单表单", "生成采购订单"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to create the form report for.", "要创建表单报告的采购订单。"),
                    F("FormReportConfigurationId", "The form-report configuration; defaults to the system's.", "表单报告配置；默认使用系统配置。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.FormReports.CreatePurchaseTransportLabel",
                "Create a purchase transport label.",
                "创建采购运输标签。",
                ["create purchase transport label", "purchase label"], ["创建采购运输标签", "采购标签"],
                fields: [
                    F("PurchaseOrderDeliveryRowId", "The purchase-order delivery row the label is for.", "标签针对的采购订单交货行。"),
                    F("PartLabelType", "The type of label (transport, label, small label, multi label...).", "标签的类型（运输、标签、小标签、多标签等）。"),
                    F("FormReportConfigurationId", "The form-report configuration; defaults to the system's.", "表单报告配置；默认使用系统配置。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.FormReports.PrintInquiry",
                "Print an inquiry form report.",
                "打印询价单表单报告。",
                ["print inquiry", "print inquiry form"], ["打印询价单", "打印询价单表单"],
                fields: [
                    F("Command", "The inquiry form-report command to print.", "要打印的询价单表单命令。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.FormReports.PrintPurchaseOrder",
                "Print a purchase-order form report.",
                "打印采购订单表单报告。",
                ["print purchase order", "print order form"], ["打印采购订单", "打印订单表单"],
                fields: [
                    F("Command", "The purchase-order form-report command to print.", "要打印的采购订单表单命令。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.FormReports.PrintPurchaseTransportLabel",
                "Print a purchase transport label.",
                "打印采购运输标签。",
                ["print purchase label", "print transport label"], ["打印采购运输标签", "打印采购标签"],
                fields: [
                    F("Command", "The transport-label command to print.", "要打印的运输标签命令。"),
                ]),

            // ---- Inquiries -----------------------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.AddCommunicationAddressInquiry",
                "Add a communication address to an inquiry.",
                "为询价单添加通信地址。",
                ["add inquiry address", "add communication address"], ["添加询价单地址", "添加通信地址"],
                fields: [
                    F("InquiryId", "The inquiry to add the address to.", "要添加地址的询价单。"),
                    F("CommunicationAddressValue", "The communication address value.", "通信地址值。"),
                    F("Type", "The communication channel (phone, fax, e-mail, cell phone).", "通信渠道（电话、传真、电子邮件、手机）。"),
                    F("RecipientOf", "The document types this address receives.", "该地址接收的单据类型。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.AddInquiryRow",
                "Add a row to an inquiry.",
                "为询价单添加行。",
                ["add inquiry row", "add inquiry line"], ["添加询价行", "添加询价单行"],
                fields: [
                    F("InquiryId", "The inquiry to add the row to.", "要添加行的询价单。"),
                    F("PartId", "The part of the row.", "行的物料。"),
                    F("OrderRowType", "The type of the row (part, additional, sum, free text).", "行的类型（物料、附加、合计、自由文本）。"),
                    F("OrderedQuantity", "The ordered quantity of the row.", "行的订购数量。"),
                    F("UnitId", "The unit of the row quantity.", "行数量的单位。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.ChangeCurrencyInquiry",
                "Change the currency of an inquiry.",
                "更改询价单的货币。",
                ["change inquiry currency", "change currency"], ["更改询价单货币", "更改货币"],
                fields: [
                    F("InquiryId", "The inquiry to change the currency for.", "要更改货币的询价单。"),
                    F("CurrencyId", "The new currency.", "新的货币。"),
                    F("ConvertPrice", "Whether to convert existing prices to the new currency.", "是否将现有价格换算为新货币。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.ChangeInquiryType",
                "Change the type of an inquiry.",
                "更改询价单的类型。",
                ["change inquiry type", "change type"], ["更改询价单类型", "更改类型"],
                fields: [
                    F("InquiryId", "The inquiry to change the type for.", "要更改类型的询价单。"),
                    F("InquiryTypeId", "The new inquiry type.", "新的询价单类型。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.ChangeSupplierInquiry",
                "Change the supplier of an inquiry.",
                "更改询价单的供应商。",
                ["change inquiry supplier", "change supplier"], ["更改询价单供应商", "更改供应商"],
                fields: [
                    F("InquiryId", "The inquiry to change the supplier for.", "要更改供应商的询价单。"),
                    F("SupplierId", "The new supplier.", "新的供应商。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.CreateInquiry",
                "Create an inquiry.",
                "创建询价单。",
                ["create inquiry", "create rfq", "new inquiry"], ["创建询价单", "新建询价单", "创建询价"],
                fields: [
                    F("SupplierId", "The supplier of the inquiry.", "询价单的供应商。"),
                    F("InquiryTypeId", "The inquiry type; defaults to the last used type.", "询价单类型；默认为上次使用的类型。"),
                    F("Rows", "The rows of the inquiry.", "询价单的行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.GetRecipientOfTypeInquiry",
                "Get the recipient of a document type on an inquiry.",
                "获取询价单上某单据类型的收件人。",
                ["get inquiry recipient", "recipient of type"], ["获取询价单收件人"],
                fields: [
                    F("InquiryId", "The inquiry to get the recipient for.", "要获取收件人的询价单。"),
                    F("RecipientOf", "The document type to get the recipient for.", "要获取收件人的单据类型。"),
                    F("Type", "The communication channel of the recipient.", "收件人的通信渠道。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.RemoveCommunicationAddressInquiry",
                "Remove a communication address from an inquiry.",
                "从询价单移除通信地址。",
                ["remove inquiry address", "remove communication address"], ["移除询价单地址", "移除通信地址"],
                fields: [
                    F("InquiryId", "The inquiry to remove the address from.", "要移除地址的询价单。"),
                    F("CommunicationAddressId", "The communication address to remove.", "要移除的通信地址。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.RemoveInquiryRow",
                "Remove a row from an inquiry.",
                "从询价单移除行。",
                ["remove inquiry row", "delete inquiry row"], ["移除询价行", "删除询价行"],
                fields: [
                    F("InquiryRowId", "The inquiry row to remove.", "要移除的询价行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.SetInquiryRowCoding",
                "Set the coding of an inquiry row.",
                "设置询价行的记账信息。",
                ["set inquiry row coding", "set row coding"], ["设置询价行记账"],
                fields: [
                    F("RowId", "The inquiry row to set the coding for.", "要设置记账信息的询价行。"),
                    F("CodingEntryId", "The coding entry of the row.", "行的记账条目。"),
                    F("AccountId", "The account of the row.", "行的科目。"),
                    F("CodingEntryElements", "The elements of the coding entry.", "记账条目的记账元素。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.SetPropertiesInquiry",
                "Set the properties of an inquiry.",
                "设置询价单的属性。",
                ["set inquiry properties", "update inquiry"], ["设置询价单属性", "更新询价单"],
                fields: [
                    F("InquiryId", "The inquiry to update.", "要更新的询价单。"),
                    F("Status", "The status of the inquiry.", "询价单的状态。"),
                    F("PaymentTermId", "The payment term of the inquiry.", "询价单的付款条款。"),
                    F("DeliveryTermId", "The delivery term of the inquiry.", "询价单的交货条款。"),
                    F("DeliveryMethodId", "The delivery method of the inquiry.", "询价单的交货方式。"),
                    F("WarehouseId", "The warehouse of the inquiry.", "询价单的仓库。"),
                    F("OurReferenceId", "Our reference (person) for the inquiry.", "询价单的我方联系人（人员）。"),
                    F("OurReferenceName", "The name of our reference.", "我方联系人的姓名。"),
                    F("BusinessContactReferenceId", "The supplier reference of the inquiry.", "询价单的供应商联系人。"),
                    F("BusinessContactReferenceName", "The name of the supplier reference.", "供应商联系人的姓名。"),
                    F("BusinessContactOrderNumber", "The supplier's order number of the inquiry.", "询价单的供应商订单号。"),
                    F("OrderDate", "The order date of the inquiry.", "询价单的订单日期。"),
                    F("Priority", "The priority of the inquiry.", "询价单的优先级。"),
                    F("PaymentTermDescription", "The description of the payment term.", "付款条款的描述。"),
                    F("GracePeriodInDays", "The grace period in days of the payment term.", "付款条款的宽限期（天）。"),
                    F("DeliveryTermDescription", "The description of the delivery term.", "交货条款的描述。"),
                    F("DeliveryMethodDescription", "The description of the delivery method.", "交货方式的描述。"),
                    F("GoodsLabel1", "The first goods label of the inquiry.", "询价单的第一个货物标签。"),
                    F("GoodsLabel2", "The second goods label of the inquiry.", "询价单的第二个货物标签。"),
                    F("InquiryDate", "The inquiry date of the inquiry.", "询价单的询价日期。"),
                    F("InquiryDescription", "The description of the inquiry.", "询价单的描述。"),
                    F("LatestContactDate", "The latest contact date of the inquiry.", "询价单的最近联系日期。"),
                    F("ValidThroughDate", "The validity end date of the inquiry.", "询价单的有效截止日期。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.UpdateCommunicationAddressInquiry",
                "Update a communication address on an inquiry.",
                "更新询价单上的通信地址。",
                ["update inquiry address", "update communication address"], ["更新询价单地址", "更新通信地址"],
                fields: [
                    F("InquiryId", "The inquiry to update.", "要更新的询价单。"),
                    F("CommunicationAddressId", "The communication address to update.", "要更新的通信地址。"),
                    F("Type", "The communication channel (phone, fax, e-mail, cell phone).", "通信渠道（电话、传真、电子邮件、手机）。"),
                    F("CommunicationAddressValue", "The communication address value.", "通信地址值。"),
                    F("RecipientOf", "The document types this address receives.", "该地址接收的单据类型。"),
                    F("Remarks", "Remarks on the communication address.", "通信地址的备注。"),
                    F("ContactName", "The contact name of the address.", "地址的联系人姓名。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.UpdateDeliveryAddressInquiry",
                "Update the delivery address of an inquiry.",
                "更新询价单的交货地址。",
                ["update inquiry delivery address", "update delivery address"], ["更新询价单交货地址", "更新交货地址"],
                fields: [
                    F("InquiryId", "The inquiry to update.", "要更新的询价单。"),
                    F("Addressee", "The addressee of the address.", "地址的收件人。"),
                    F("Field1", "The first address line.", "地址第一行。"),
                    F("Field2", "The second address line.", "地址第二行。"),
                    F("Field3", "The third address line.", "地址第三行。"),
                    F("Field4", "The fourth address line.", "地址第四行。"),
                    F("Field5", "The fifth address line.", "地址第五行。"),
                    F("Locality", "The locality (city) of the address.", "地址的所在地（城市）。"),
                    F("Region", "The region of the address.", "地址的地区。"),
                    F("PostalCode", "The postal code of the address.", "地址的邮政编码。"),
                    F("PostalCodeId", "The postal code record of the address.", "地址的邮政编码记录。"),
                    F("FormReportTranslationGroupId", "The form-report translation group of the address.", "地址的表单报告翻译组。"),
                    F("LanguageId", "The language of the address.", "地址的语言。"),
                    F("SetAddressCountry", "Sets the country of the address together with its format.", "连同格式一起设置地址的国家。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.UpdateInquiryRow",
                "Update an inquiry row.",
                "更新询价行。",
                ["update inquiry row", "update inquiry line"], ["更新询价行", "修改询价行"],
                fields: [
                    F("RowId", "The inquiry row to update.", "要更新的询价行。"),
                    F("PartId", "The part of the row.", "行的物料。"),
                    F("OrderRowType", "The type of the row (part, additional, sum, free text).", "行的类型（物料、附加、合计、自由文本）。"),
                    F("OrderedQuantity", "The ordered quantity of the row.", "行的订购数量。"),
                    F("DeliveryDate", "The delivery date of the row.", "行的交货日期。"),
                    F("UnitId", "The unit of the row quantity.", "行数量的单位。"),
                    F("AdditionalPartCode", "The additional part code of the row.", "行的附加物料代码。"),
                    F("PartDescription", "The part description of the row.", "行的物料描述。"),
                    F("TextRowData", "The free-text data of the row.", "行的自由文本数据。"),
                    F("SubRowContent", "The sub-row content of the row.", "行的子行内容。"),
                    F("RowsGoodsLabel", "The goods label of the row.", "行的货物标签。"),
                    F("Price", "The price of the row.", "行的价格。"),
                    F("SetupPrice", "The setup price of the row.", "行的准备价格。"),
                    F("Discount", "The discount of the row.", "行的折扣。"),
                    F("PriceLockedFromAutomaticChanges", "Whether the price is locked from automatic changes.", "价格是否锁定以防止自动变更。"),
                    F("WarehouseId", "The warehouse of the row.", "行的仓库。"),
                    F("RevisionId", "The part revision of the row.", "行的物料修订版。"),
                    F("StatisticalGoodsCodeId", "The statistical goods code of the row.", "行的统计货物代码。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Inquiries.UpdateMailingAddressInquiry",
                "Update the mailing address of an inquiry.",
                "更新询价单的邮寄地址。",
                ["update inquiry mailing address", "update mailing address"], ["更新询价单邮寄地址", "更新邮寄地址"],
                fields: [
                    F("InquiryId", "The inquiry to update.", "要更新的询价单。"),
                    F("Addressee", "The addressee of the address.", "地址的收件人。"),
                    F("Field1", "The first address line.", "地址第一行。"),
                    F("Field2", "The second address line.", "地址第二行。"),
                    F("Field3", "The third address line.", "地址第三行。"),
                    F("Field4", "The fourth address line.", "地址第四行。"),
                    F("Field5", "The fifth address line.", "地址第五行。"),
                    F("Locality", "The locality (city) of the address.", "地址的所在地（城市）。"),
                    F("Region", "The region of the address.", "地址的地区。"),
                    F("PostalCode", "The postal code of the address.", "地址的邮政编码。"),
                    F("PostalCodeId", "The postal code record of the address.", "地址的邮政编码记录。"),
                    F("FormReportTranslationGroupId", "The form-report translation group of the address.", "地址的表单报告翻译组。"),
                    F("LanguageId", "The language of the address.", "地址的语言。"),
                    F("SetAddressCountry", "Sets the country of the address together with its format.", "连同格式一起设置地址的国家。"),
                ]),

            // ---- PurchaseOrderAdvices ------------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrderAdvices.AddPurchaseOrderAdviceRow",
                "Add a row to a purchase-order advice.",
                "为采购订单发货通知添加行。",
                ["add advice row", "add purchase advice row"], ["添加发货通知行", "添加通知行"],
                fields: [
                    F("PurchaseOrderAdviceId", "The advice to add the row to; not needed when part of a create-advice command.", "要添加行的发货通知；创建通知命令中可省略。"),
                    F("PurchaseOrderRowId", "The purchase-order row the advice concerns.", "通知所针对的采购订单行。"),
                    F("Quantity", "The advised quantity.", "通知数量。"),
                    F("ProductRecordReportings", "The product-record (batch/serial) reportings of the advice row.", "通知行的产品记录（批次/序列号）上报。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrderAdvices.CreatePurchaseOrderAdvice",
                "Create a purchase-order advice.",
                "创建采购订单发货通知。",
                ["create advice", "create dispatch advice"], ["创建发货通知", "创建交货通知"],
                fields: [
                    F("SupplierId", "The supplier of the advice.", "发货通知的供应商。"),
                    F("DispatchDate", "The dispatch date of the goods.", "货物的发货日期。"),
                    F("DeliveryNoteNumber", "The delivery-note number of the advice.", "发货通知的交货单号。"),
                    F("AdviceRowReportings", "The rows of the advice.", "发货通知的行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrderAdvices.RemovePurchaseOrderAdvice",
                "Remove a purchase-order advice.",
                "删除采购订单发货通知。",
                ["remove advice", "delete dispatch advice"], ["删除发货通知", "移除发货通知"],
                fields: [
                    F("PurchaseOrderAdviceId", "The advice to remove.", "要删除的发货通知。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrderAdvices.RemovePurchaseOrderAdviceRow",
                "Remove a row from a purchase-order advice.",
                "从采购订单发货通知移除行。",
                ["remove advice row"], ["移除发货通知行"],
                fields: [
                    F("PurchaseOrderAdviceRowId", "The advice row to remove.", "要移除的通知行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrderAdvices.SetPropertiesPurchaseOrderAdvice",
                "Set the properties of a purchase-order advice.",
                "设置采购订单发货通知的属性。",
                ["set advice properties", "update advice"], ["设置发货通知属性", "更新发货通知"],
                fields: [
                    F("PurchaseOrderAdviceId", "The advice to update.", "要更新的发货通知。"),
                    F("DeliveryNoteNumber", "The delivery-note number of the advice.", "发货通知的交货单号。"),
                    F("DispatchDate", "The dispatch date of the goods.", "货物的发货日期。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrderAdvices.UpdatePurchaseOrderAdviceRow",
                "Update a purchase-order advice row.",
                "更新采购订单发货通知行。",
                ["update advice row"], ["更新发货通知行"],
                fields: [
                    F("PurchaseOrderAdviceRowId", "The advice row to update.", "要更新的通知行。"),
                    F("Status", "The status of the row (registered, partially delivered, history).", "行的状态（已登记、部分交货、历史）。"),
                    F("Quantity", "The advised quantity.", "通知数量。"),
                    F("UnitId", "The unit of the advised quantity.", "通知数量的单位。"),
                ]),

            // ---- PurchaseOrderDeliveries ---------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrderDeliveries.UpdatePurchaseOrderDeliveryRow",
                "Update a purchase-order delivery row.",
                "更新采购订单交货行。",
                ["update delivery row", "update arrival row"], ["更新交货行", "更新到货行"],
                fields: [
                    F("PurchaseOrderDeliveryRowId", "The delivery row to update.", "要更新的交货行。"),
                ]),

            // ---- PurchaseOrders ------------------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.AddCommunicationAddressPurchaseOrder",
                "Add a communication address to a purchase order.",
                "为采购订单添加通信地址。",
                ["add purchase order address", "add communication address"], ["添加采购订单地址", "添加通信地址"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to add the address to.", "要添加地址的采购订单。"),
                    F("CommunicationAddressValue", "The communication address value.", "通信地址值。"),
                    F("Type", "The communication channel (phone, fax, e-mail, cell phone).", "通信渠道（电话、传真、电子邮件、手机）。"),
                    F("RecipientOf", "The document types this address receives.", "该地址接收的单据类型。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.AddPurchaseOrderActivity",
                "Add an activity to a purchase order.",
                "为采购订单添加活动。",
                ["add purchase order activity", "add activity"], ["添加采购订单活动", "添加活动"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to add the activity to.", "要添加活动的采购订单。"),
                    F("ActivityTypeId", "The activity type of the activity.", "活动的活动类型。"),
                    F("ResponsibleUserId", "The user responsible for the activity.", "负责该活动的用户。"),
                    F("PlannedCompletionDate", "The planned completion date of the activity.", "活动的计划完成日期。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.AddPurchaseOrderRow",
                "Add a row to a purchase order.",
                "为采购订单添加行。",
                ["add purchase order row", "add order row", "add row"], ["添加采购订单行", "添加订单行", "添加行"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to add the row to.", "要添加行的采购订单。"),
                    F("PartId", "The part of the row.", "行的物料。"),
                    F("OrderRowType", "The type of the row (part, additional, sum, free text).", "行的类型（物料、附加、合计、自由文本）。"),
                    F("OrderedQuantity", "The ordered quantity of the row.", "行的订购数量。"),
                    F("UnitId", "The unit of the row quantity.", "行数量的单位。"),
                    F("WarehouseId", "The warehouse of the row; defaults to the purchase order's warehouse.", "行的仓库；默认为采购订单的仓库。"),
                    F("DeliveryDate", "The delivery date of the row.", "行的交货日期。"),
                    F("CodingRows", "The coding rows of the row.", "行的记账行。"),
                    F("PartialQuantities", "The partial quantities of the row.", "行的零头数量。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.AddSupplierActivity",
                "Add an activity to a supplier.",
                "为供应商添加活动。",
                ["add supplier activity", "add activity to supplier"], ["添加供应商活动", "添加供应商跟进"],
                fields: [
                    F("SupplierId", "The supplier to add the activity to.", "要添加活动的供应商。"),
                    F("ActivityTypeId", "The activity type of the activity.", "活动的活动类型。"),
                    F("ResponsibleUserId", "The user responsible for the activity.", "负责该活动的用户。"),
                    F("PlannedCompletionDate", "The planned completion date of the activity.", "活动的计划完成日期。"),
                    F("PurchaseOrderId", "The purchase order the activity is linked to, if any.", "活动关联的采购订单（如有）。"),
                    F("SupplierReferenceId", "The supplier reference the activity is linked to, if any.", "活动关联的供应商联系人（如有）。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.ChangeAccountGroupPurchaseOrder",
                "Change the account group of a purchase order.",
                "更改采购订单的科目组。",
                ["change account group", "change supplier account group"], ["更改科目组", "更改供应商科目组"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to change the account group for.", "要更改科目组的采购订单。"),
                    F("AccountGroupId", "The new supplier account group.", "新的供应商科目组。"),
                    F("UpdateCodings", "Whether to update the row codings.", "是否更新行的记账信息。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.ChangeCurrencyPurchaseOrder",
                "Change the currency of a purchase order.",
                "更改采购订单的货币。",
                ["change purchase order currency", "change currency"], ["更改采购订单货币", "更改货币"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to change the currency for.", "要更改货币的采购订单。"),
                    F("CurrencyId", "The new currency.", "新的货币。"),
                    F("ConvertPrice", "Whether to convert existing prices to the new currency.", "是否将现有价格换算为新货币。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.ChangeOrderTypePurchaseOrder",
                "Change the type of a purchase order.",
                "更改采购订单的类型。",
                ["change purchase order type", "change order type"], ["更改采购订单类型", "更改订单类型"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to change the type for.", "要更改类型的采购订单。"),
                    F("OrderTypeId", "The new purchase-order type.", "新的采购订单类型。"),
                    F("UpdatePriority", "Whether to update the priority from the type.", "是否从类型更新优先级。"),
                    F("UpdateCodings", "Whether to update the codings from the type.", "是否从类型更新记账信息。"),
                    F("UpdateVatRates", "Whether to update the VAT rates from the type.", "是否从类型更新增值税率。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.ChangeSupplierPurchaseOrder",
                "Change the supplier of a purchase order.",
                "更改采购订单的供应商。",
                ["change purchase order supplier", "change supplier"], ["更改采购订单供应商", "更改供应商"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to change the supplier for.", "要更改供应商的采购订单。"),
                    F("SupplierId", "The new supplier.", "新的供应商。"),
                    F("UpdatePrices", "Whether to update the row prices from the supplier.", "是否从供应商更新行价格。"),
                    F("UpdateDeliveryDates", "Whether to update the delivery dates.", "是否更新交货日期。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.CreatePurchaseOrder",
                "Create a purchase order.",
                "创建采购订单。",
                ["create purchase order", "create order", "new purchase order"], ["创建采购订单", "新建采购订单", "创建订单"],
                fields: [
                    F("SupplierId", "The supplier of the purchase order.", "采购订单的供应商。"),
                    F("OrderTypeId", "The purchase-order type; defaults to the last used type.", "采购订单类型；默认为上次使用的类型。"),
                    F("Rows", "The rows of the purchase order.", "采购订单的行。"),
                    F("WarehouseId", "The warehouse of the purchase order; defaults to the current warehouse.", "采购订单的仓库；默认为当前仓库。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.GetAvailableBlanketOrderRows",
                "Get the blanket-order rows available for a purchase-order row.",
                "获取采购订单行可用的采购框架协议行。",
                ["get available blanket rows", "blanket rows for row"], ["获取可用框架协议行"],
                fields: [
                    F("PurchaseOrderRowId", "The purchase-order row to get available blanket rows for.", "要获取可用框架协议行的采购订单行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.GetRecipientOfTypePurchaseOrder",
                "Get the recipient of a document type on a purchase order.",
                "获取采购订单上某单据类型的收件人。",
                ["get purchase order recipient", "recipient of type"], ["获取采购订单收件人"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to get the recipient for.", "要获取收件人的采购订单。"),
                    F("RecipientOf", "The document type to get the recipient for.", "要获取收件人的单据类型。"),
                    F("Type", "The communication channel of the recipient.", "收件人的通信渠道。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.RemoveCommunicationAddressPurchaseOrder",
                "Remove a communication address from a purchase order.",
                "从采购订单移除通信地址。",
                ["remove purchase order address", "remove communication address"], ["移除采购订单地址", "移除通信地址"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to remove the address from.", "要移除地址的采购订单。"),
                    F("CommunicationAddressId", "The communication address to remove.", "要移除的通信地址。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.RemovePurchaseOrderActivity",
                "Remove an activity from a purchase order.",
                "从采购订单移除活动。",
                ["remove purchase order activity", "remove activity"], ["移除采购订单活动", "移除活动"],
                fields: [
                    F("PurchaseOrderActivityId", "The purchase-order activity to remove.", "要移除的采购订单活动。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.RemovePurchaseOrderRow",
                "Remove a row from a purchase order.",
                "从采购订单移除行。",
                ["remove purchase order row", "remove order row"], ["移除采购订单行", "删除订单行"],
                fields: [
                    F("PurchaseOrderRowId", "The purchase-order row to remove.", "要移除的采购订单行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.RemoveSupplierActivity",
                "Remove an activity from a supplier.",
                "从供应商移除活动。",
                ["remove supplier activity"], ["移除供应商活动"],
                fields: [
                    F("SupplierActivityId", "The supplier activity to remove.", "要移除的供应商活动。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.SetIsConfirmedPurchaseOrder",
                "Set whether a purchase order is confirmed.",
                "设置采购订单是否已确认。",
                ["set purchase order confirmed", "confirm order"], ["设置采购订单确认", "确认订单"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to set the confirmation state for.", "要设置确认状态的采购订单。"),
                    F("IsConfirmed", "Whether the purchase order is confirmed.", "采购订单是否已确认。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.SetPropertiesPurchaseOrder",
                "Set the properties of a purchase order.",
                "设置采购订单的属性。",
                ["set purchase order properties", "update purchase order"], ["设置采购订单属性", "更新采购订单"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to update.", "要更新的采购订单。"),
                    F("Status", "The status of the purchase order.", "采购订单的状态。"),
                    F("PaymentTermId", "The payment term of the purchase order.", "采购订单的付款条款。"),
                    F("DeliveryTermId", "The delivery term of the purchase order.", "采购订单的交货条款。"),
                    F("DeliveryMethodId", "The delivery method of the purchase order.", "采购订单的交货方式。"),
                    F("WarehouseId", "The warehouse of the purchase order.", "采购订单的仓库。"),
                    F("ProjectId", "The project of the purchase order.", "采购订单的项目。"),
                    F("OurReferenceId", "Our reference (person) for the purchase order.", "采购订单的我方联系人（人员）。"),
                    F("OurReferenceName", "The name of our reference.", "我方联系人的姓名。"),
                    F("BusinessContactReferenceId", "The supplier reference of the purchase order.", "采购订单的供应商联系人。"),
                    F("BusinessContactReferenceName", "The name of the supplier reference.", "供应商联系人的姓名。"),
                    F("BusinessContactOrderNumber", "The supplier's order number of the purchase order.", "采购订单的供应商订单号。"),
                    F("OrderDate", "The order date of the purchase order.", "采购订单的订单日期。"),
                    F("Priority", "The priority of the purchase order.", "采购订单的优先级。"),
                    F("InvoiceBusinessContactId", "The invoice business contact of the purchase order.", "采购订单的开票业务联系人。"),
                    F("PaymentTermDescription", "The description of the payment term.", "付款条款的描述。"),
                    F("GracePeriodInDays", "The grace period in days of the payment term.", "付款条款的宽限期（天）。"),
                    F("DeliveryTermDescription", "The description of the delivery term.", "交货条款的描述。"),
                    F("DeliveryMethodDescription", "The description of the delivery method.", "交货方式的描述。"),
                    F("GoodsLabel1", "The first goods label of the purchase order.", "采购订单的第一个货物标签。"),
                    F("GoodsLabel2", "The second goods label of the purchase order.", "采购订单的第二个货物标签。"),
                    F("CategoryString", "The category string of the purchase order.", "采购订单的类别字符串。"),
                    F("TransportTime", "The transport time of the purchase order.", "采购订单的运输时间。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.SetPurchaseOrderRowBlanketOrder",
                "Set the blanket-order row a purchase-order row is called off from.",
                "设置采购订单行所依据的采购框架协议行。",
                ["set row blanket order", "call off from blanket"], ["设置行框架协议", "按框架协议下单"],
                fields: [
                    F("PurchaseOrderRowId", "The purchase-order row to set the blanket row for.", "要设置框架协议行的采购订单行。"),
                    F("BlanketOrderPurchaseRowId", "The blanket-order row to call off from.", "所依据的采购框架协议行。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.SetPurchaseOrderRowCoding",
                "Set the coding of a purchase-order row.",
                "设置采购订单行的记账信息。",
                ["set purchase order row coding", "set row coding"], ["设置采购订单行记账"],
                fields: [
                    F("RowId", "The purchase-order row to set the coding for.", "要设置记账信息的采购订单行。"),
                    F("CodingEntryId", "The coding entry of the row.", "行的记账条目。"),
                    F("AccountId", "The account of the row.", "行的科目。"),
                    F("CodingEntryElements", "The elements of the coding entry.", "记账条目的记账元素。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.SetRowIsConfirmedPurchaseOrder",
                "Set whether a purchase-order row is confirmed.",
                "设置采购订单行是否已确认。",
                ["set row confirmed", "confirm row"], ["设置行确认", "确认订单行"],
                fields: [
                    F("PurchaseOrderRowId", "The purchase-order row to set the confirmation state for.", "要设置确认状态的采购订单行。"),
                    F("IsConfirmed", "Whether the row is confirmed.", "该行是否已确认。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.UpdateCommunicationAddressPurchaseOrder",
                "Update a communication address on a purchase order.",
                "更新采购订单上的通信地址。",
                ["update purchase order address", "update communication address"], ["更新采购订单地址", "更新通信地址"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to update.", "要更新的采购订单。"),
                    F("CommunicationAddressId", "The communication address to update.", "要更新的通信地址。"),
                    F("Type", "The communication channel (phone, fax, e-mail, cell phone).", "通信渠道（电话、传真、电子邮件、手机）。"),
                    F("CommunicationAddressValue", "The communication address value.", "通信地址值。"),
                    F("RecipientOf", "The document types this address receives.", "该地址接收的单据类型。"),
                    F("Remarks", "Remarks on the communication address.", "通信地址的备注。"),
                    F("ContactName", "The contact name of the address.", "地址的联系人姓名。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.UpdateDeliveryAddressPurchaseOrder",
                "Update the delivery address of a purchase order.",
                "更新采购订单的交货地址。",
                ["update purchase order delivery address", "update delivery address"], ["更新采购订单交货地址", "更新交货地址"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to update.", "要更新的采购订单。"),
                    F("Addressee", "The addressee of the address.", "地址的收件人。"),
                    F("Field1", "The first address line.", "地址第一行。"),
                    F("Field2", "The second address line.", "地址第二行。"),
                    F("Field3", "The third address line.", "地址第三行。"),
                    F("Field4", "The fourth address line.", "地址第四行。"),
                    F("Field5", "The fifth address line.", "地址第五行。"),
                    F("Locality", "The locality (city) of the address.", "地址的所在地（城市）。"),
                    F("Region", "The region of the address.", "地址的地区。"),
                    F("PostalCode", "The postal code of the address.", "地址的邮政编码。"),
                    F("PostalCodeId", "The postal code record of the address.", "地址的邮政编码记录。"),
                    F("FormReportTranslationGroupId", "The form-report translation group of the address.", "地址的表单报告翻译组。"),
                    F("LanguageId", "The language of the address.", "地址的语言。"),
                    F("SetAddressCountry", "Sets the country of the address together with its format.", "连同格式一起设置地址的国家。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.UpdateMailingAddressPurchaseOrder",
                "Update the mailing address of a purchase order.",
                "更新采购订单的邮寄地址。",
                ["update purchase order mailing address", "update mailing address"], ["更新采购订单邮寄地址", "更新邮寄地址"],
                fields: [
                    F("PurchaseOrderId", "The purchase order to update.", "要更新的采购订单。"),
                    F("Addressee", "The addressee of the address.", "地址的收件人。"),
                    F("Field1", "The first address line.", "地址第一行。"),
                    F("Field2", "The second address line.", "地址第二行。"),
                    F("Field3", "The third address line.", "地址第三行。"),
                    F("Field4", "The fourth address line.", "地址第四行。"),
                    F("Field5", "The fifth address line.", "地址第五行。"),
                    F("Locality", "The locality (city) of the address.", "地址的所在地（城市）。"),
                    F("Region", "The region of the address.", "地址的地区。"),
                    F("PostalCode", "The postal code of the address.", "地址的邮政编码。"),
                    F("PostalCodeId", "The postal code record of the address.", "地址的邮政编码记录。"),
                    F("FormReportTranslationGroupId", "The form-report translation group of the address.", "地址的表单报告翻译组。"),
                    F("LanguageId", "The language of the address.", "地址的语言。"),
                    F("SetAddressCountry", "Sets the country of the address together with its format.", "连同格式一起设置地址的国家。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.UpdatePurchaseOrderActivity",
                "Update a purchase-order activity.",
                "更新采购订单活动。",
                ["update purchase order activity", "update activity"], ["更新采购订单活动", "更新活动"],
                fields: [
                    F("PurchaseOrderActivityId", "The activity to update.", "要更新的活动。"),
                    F("ActivityTypeId", "The activity type of the activity.", "活动的活动类型。"),
                    F("ResponsibleUserId", "The user responsible for the activity.", "负责该活动的用户。"),
                    F("PlannedCompletionDate", "The planned completion date of the activity.", "活动的计划完成日期。"),
                    F("Status", "The status of the activity.", "活动的状态。"),
                    F("CompletionDate", "The actual completion date of the activity.", "活动的实际完成日期。"),
                    F("CompletedByUserId", "The user who completed the activity.", "完成该活动的用户。"),
                    F("Description", "The description of the activity.", "活动的描述。"),
                    F("Reminder", "Whether a reminder is created for the activity.", "是否为活动创建提醒。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.UpdatePurchaseOrderRow",
                "Update a purchase-order row.",
                "更新采购订单行。",
                ["update purchase order row", "update order row"], ["更新采购订单行", "更新订单行"],
                fields: [
                    F("RowId", "The purchase-order row to update.", "要更新的采购订单行。"),
                    F("PartId", "The part of the row.", "行的物料。"),
                    F("OrderRowType", "The type of the row (part, additional, sum, free text).", "行的类型（物料、附加、合计、自由文本）。"),
                    F("OrderedQuantity", "The ordered quantity of the row.", "行的订购数量。"),
                    F("DeliveryDate", "The delivery date of the row.", "行的交货日期。"),
                    F("UnitId", "The unit of the row quantity.", "行数量的单位。"),
                    F("DesiredDeliveryDate", "The desired delivery date of the row.", "行的期望交货日期。"),
                    F("DelayReasonId", "The delay reason of the row.", "行的延迟原因。"),
                    F("ConfirmedDelayed", "Whether the delay is confirmed.", "延迟是否已确认。"),
                    F("PartialQuantities", "The partial quantities of the row.", "行的零头数量。"),
                    F("VatRateId", "The VAT rate of the row.", "行的增值税率。"),
                    F("SupplierDrawingNumber", "The supplier's drawing number of the row.", "行的供应商图纸号。"),
                    F("RevisionId", "The part revision of the row.", "行的物料修订版。"),
                    F("StatisticalGoodsCodeId", "The statistical goods code of the row.", "行的统计货物代码。"),
                    F("AdditionalPartCode", "The additional part code of the row.", "行的附加物料代码。"),
                    F("PartDescription", "The part description of the row.", "行的物料描述。"),
                    F("TextRowData", "The free-text data of the row.", "行的自由文本数据。"),
                    F("SubRowContent", "The sub-row content of the row.", "行的子行内容。"),
                    F("RowsGoodsLabel", "The goods label of the row.", "行的货物标签。"),
                    F("Price", "The price of the row.", "行的价格。"),
                    F("SetupPrice", "The setup price of the row.", "行的准备价格。"),
                    F("Discount", "The discount of the row.", "行的折扣。"),
                    F("PriceLockedFromAutomaticChanges", "Whether the price is locked from automatic changes.", "价格是否锁定以防止自动变更。"),
                    F("WarehouseId", "The warehouse of the row.", "行的仓库。"),
                    F("Position", "The position of the row.", "行的位置。"),
                    F("SupplierOrderNumber", "The supplier's order number of the row.", "行的供应商订单号。"),
                    F("SupplierOrderRowPosition", "The supplier's order-row position of the row.", "行的供应商订单行位置。"),
                    F("SupplierRevisionNumber", "The supplier's revision number of the row.", "行的供应商修订号。"),
                    F("RowNotes", "Notes on the row.", "行的备注。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.PurchaseOrders.UpdateSupplierActivity",
                "Update a supplier activity.",
                "更新供应商活动。",
                ["update supplier activity"], ["更新供应商活动"],
                fields: [
                    F("SupplierActivityId", "The activity to update.", "要更新的活动。"),
                    F("ActivityTypeId", "The activity type of the activity.", "活动的活动类型。"),
                    F("ResponsibleUserId", "The user responsible for the activity.", "负责该活动的用户。"),
                    F("PlannedCompletionDate", "The planned completion date of the activity.", "活动的计划完成日期。"),
                    F("Description", "The description of the activity.", "活动的描述。"),
                    F("PurchaseOrderId", "The purchase order the activity is linked to, if any.", "活动关联的采购订单（如有）。"),
                    F("Reminder", "Whether a reminder is created for the activity.", "是否为活动创建提醒。"),
                    F("SupplierReferenceId", "The supplier reference the activity is linked to, if any.", "活动关联的供应商联系人（如有）。"),
                ]),

            // ---- ReceivingInspection ------------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.ReceivingInspection.ReportReceivingInspection",
                "Report a receiving inspection on purchase-order delivery rows.",
                "上报采购订单交货行的收货检验。",
                ["report receiving inspection", "receiving inspection", "inspection reporting"], ["上报收货检验", "收货检验", "来料检验"],
                fields: [
                    F("Rows", "The receiving-inspection rows to report.", "要上报的收货检验行。"),
                    F("ReportingEmployeeId", "The employee making the reporting; defaults to the session user's employee.", "进行上报的员工；默认为当前用户的员工。"),
                ]),

            // ---- Suppliers -----------------------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.AddBankAccountSupplier",
                "Add a bank account to a supplier.",
                "为供应商添加银行账户。",
                ["add supplier bank account", "add bank account"], ["添加供应商银行账户", "添加银行账户"],
                fields: [
                    F("SupplierId", "The supplier to add the bank account to.", "要添加银行账户的供应商。"),
                    F("Number", "The bank account number.", "银行账号。"),
                    F("Type", "The bank account format (IBAN, BBAN, UPIC, miscellaneous).", "银行账户格式（IBAN、BBAN、UPIC 或其他）。"),
                    F("CurrencyId", "The currency of the bank account; defaults to the supplier currency.", "银行账户的货币；默认为供应商货币。"),
                    F("CountryId", "The country of the bank account; defaults to the supplier's mailing-address country.", "银行账户的国家；默认为供应商邮寄地址国家。"),
                    F("Addressee", "The addressee of the bank account.", "银行账户的收件人。"),
                    F("CentralBankCodeId", "The central bank code of the bank.", "银行的中央银行代码。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.AddCommunicationAddressSupplier",
                "Add a communication address to a supplier.",
                "为供应商添加通信地址。",
                ["add supplier address", "add communication address"], ["添加供应商地址", "添加通信地址"],
                fields: [
                    F("SupplierId", "The supplier to add the address to.", "要添加地址的供应商。"),
                    F("CommunicationAddressValue", "The communication address value.", "通信地址值。"),
                    F("Type", "The communication channel (phone, fax, e-mail, cell phone).", "通信渠道（电话、传真、电子邮件、手机）。"),
                    F("RecipientOf", "The document types this address receives.", "该地址接收的单据类型。"),
                    F("DeliveryAddressId", "The delivery address the communication address is linked to, if any.", "通信地址关联的交货地址（如有）。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.AddSupplierDeliveryAddress",
                "Add a delivery address to a supplier.",
                "为供应商添加交货地址。",
                ["add supplier delivery address", "add delivery address"], ["添加供应商交货地址", "添加交货地址"],
                fields: [
                    F("SupplierId", "The supplier to add the delivery address to.", "要添加交货地址的供应商。"),
                    F("SetAsDefault", "Whether to set the address as the supplier's default.", "是否将该地址设为供应商的默认地址。"),
                    F("WarehouseId", "The warehouse the delivery settings apply to.", "交货设置适用的仓库。"),
                    F("VatRateId", "The default VAT rate of the delivery address.", "交货地址的默认增值税率。"),
                    F("VatGroupId", "The VAT group of the delivery address.", "交货地址的增值税组。"),
                    F("DeliveryMethodId", "The delivery method of the delivery address.", "交货地址的交货方式。"),
                    F("DeliveryTermId", "The delivery term of the delivery address.", "交货地址的交货条款。"),
                    F("ConsigneeReferenceId", "The consignee reference (person) of the delivery address.", "交货地址的收货人联系人。"),
                    F("ConsigneeReferenceName", "The name of the consignee reference.", "收货人联系人的姓名。"),
                    F("Destination", "The destination of the delivery.", "交货的目的地。"),
                    F("DestinationForDeliveryTerm", "The destination used for the delivery term.", "交货条款使用的地点。"),
                    F("DeliveryInstruction", "Delivery instructions for the address.", "该地址的交货说明。"),
                    F("DeliveryWeekdays", "The weekdays on which deliveries are made.", "进行交货的工作日。"),
                    F("TransportTime", "The transport time in days.", "运输时间（天）。"),
                    F("CustomerAccountGroupId", "The customer account group for the delivery address.", "交货地址的客户科目组。"),
                    F("SupplierAccountGroupId", "The supplier account group for the delivery address.", "交货地址的供应商科目组。"),
                    F("Addressee", "The addressee of the address.", "地址的收件人。"),
                    F("Field1", "The first address line.", "地址第一行。"),
                    F("Field2", "The second address line.", "地址第二行。"),
                    F("Field3", "The third address line.", "地址第三行。"),
                    F("Field4", "The fourth address line.", "地址第四行。"),
                    F("Field5", "The fifth address line.", "地址第五行。"),
                    F("Locality", "The locality (city) of the address.", "地址的所在地（城市）。"),
                    F("Region", "The region of the address.", "地址的地区。"),
                    F("PostalCode", "The postal code of the address.", "地址的邮政编码。"),
                    F("LanguageId", "The language of the address.", "地址的语言。"),
                    F("FormReportTranslationGroupId", "The form-report translation group of the address.", "地址的表单报告翻译组。"),
                    F("SetAddressCountry", "Sets the country of the address together with its format.", "连同格式一起设置地址的国家。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.AddSupplierReference",
                "Add a reference to a supplier.",
                "为供应商添加联系人。",
                ["add supplier reference", "add reference"], ["添加供应商联系人", "添加联系人"],
                fields: [
                    F("SupplierId", "The supplier to add the reference to.", "要添加联系人的供应商。"),
                    F("Name", "The name of the reference.", "联系人的姓名。"),
                    F("Comment", "A comment on the reference.", "联系人的备注。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.CreateOtherSupplierNumber",
                "Create an additional number for a supplier.",
                "为供应商创建其他编号。",
                ["create other supplier number", "add supplier number"], ["创建供应商其他编号", "添加供应商编号"],
                fields: [
                    F("SupplierId", "The supplier to create the number for.", "要创建编号的供应商。"),
                    F("Number", "The additional number.", "附加编号。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.CreateSupplier",
                "Create a supplier.",
                "创建供应商。",
                ["create supplier", "new supplier", "create vendor"], ["创建供应商", "新建供应商", "创建厂商"],
                fields: [
                    F("Name", "The name of the supplier.", "供应商的名称。"),
                    F("Code", "The unique supplier code; defaults to the number series.", "供应商的唯一代码；默认使用编号系列。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.RemoveBankAccountSupplier",
                "Remove a bank account from a supplier.",
                "从供应商移除银行账户。",
                ["remove supplier bank account", "remove bank account"], ["移除供应商银行账户", "移除银行账户"],
                fields: [
                    F("BankAccountId", "The bank account to remove.", "要移除的银行账户。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.RemoveCommunicationAddressSupplier",
                "Remove a communication address from a supplier.",
                "从供应商移除通信地址。",
                ["remove supplier address", "remove communication address"], ["移除供应商地址", "移除通信地址"],
                fields: [
                    F("CommunicationAddressId", "The communication address to remove.", "要移除的通信地址。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.RemoveOtherSupplierNumber",
                "Remove an additional number from a supplier.",
                "从供应商移除其他编号。",
                ["remove other supplier number"], ["移除供应商其他编号"],
                fields: [
                    F("OtherSupplierNumberId", "The other supplier number to remove.", "要移除的其他编号。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.RemoveSupplierDeliveryAddress",
                "Remove a delivery address from a supplier.",
                "从供应商移除交货地址。",
                ["remove supplier delivery address", "remove delivery address"], ["移除供应商交货地址", "移除交货地址"],
                fields: [
                    F("Id", "The supplier delivery-address record to remove.", "要移除的供应商交货地址记录。"),
                    F("DeliveryAddressId", "The delivery address to remove.", "要移除的交货地址。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.RemoveSupplierReference",
                "Remove a reference from a supplier.",
                "从供应商移除联系人。",
                ["remove supplier reference", "remove reference"], ["移除供应商联系人", "移除联系人"],
                fields: [
                    F("SupplierId", "The supplier to remove the reference from.", "要移除联系人的供应商。"),
                    F("ReferenceId", "The reference to remove.", "要移除的联系人。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.SetPropertiesSupplier",
                "Set the properties of a supplier.",
                "设置供应商的属性。",
                ["set supplier properties", "update supplier"], ["设置供应商属性", "更新供应商"],
                fields: [
                    F("SupplierId", "The supplier to update.", "要更新的供应商。"),
                    F("Name", "The name of the supplier.", "供应商的名称。"),
                    F("VatNumber", "The VAT number of the supplier.", "供应商的增值税号。"),
                    F("PaymentTermId", "The payment term of the supplier.", "供应商的付款条款。"),
                    F("PaymentMethodId", "The payment method of the supplier.", "供应商的付款方式。"),
                    F("VatGroupId", "The VAT group of the supplier.", "供应商的增值税组。"),
                    F("CurrencyId", "The currency of the supplier.", "供应商的货币。"),
                    F("CurrencyExchangeTypeId", "The exchange-rate type of the supplier.", "供应商的汇率类型。"),
                    F("Role", "The role of the supplier.", "供应商的角色。"),
                    F("ResponseTimeId", "The response time of the supplier.", "供应商的响应时间。"),
                    F("Discount", "The discount of the supplier.", "供应商的折扣。"),
                    F("DiscountCategoryId", "The discount category of the supplier.", "供应商的折扣类别。"),
                    F("LanguageId", "The language of the supplier.", "供应商的语言。"),
                    F("ReceivingInspectionType", "The receiving-inspection type of the supplier (none, always, variable).", "供应商的收货检验类型（无、始终、变动）。"),
                    F("ArrivalReportingInstruction", "The arrival-reporting instruction of the supplier.", "供应商的到货上报说明。"),
                    F("DefaultReferenceId", "The default reference of the supplier.", "供应商的默认联系人。"),
                    F("EORINumber", "The EORI number of the supplier.", "供应商的 EORI 编号。"),
                    F("AlternativeName", "The alternative name of the supplier.", "供应商的别名。"),
                    F("BankGiroNo", "The bank giro number of the supplier.", "供应商的银行转账号。"),
                    F("PlusGiroNo", "The plus giro number of the supplier.", "供应商的邮政转账号。"),
                    F("CategoryString", "The category string of the supplier.", "供应商的类别字符串。"),
                    F("CorporationIdentificationNumber", "The corporation identification number of the supplier.", "供应商的公司注册号。"),
                    F("FixedReferenceNumber", "The fixed reference number of the supplier.", "供应商的固定参考号。"),
                    F("InvoiceSupplierId", "The supplier that invoices for this supplier.", "为本供应商开票的供应商。"),
                    F("IsPrivateSupplier", "Whether the supplier is a private (personal) supplier.", "供应商是否为私人（个人）供应商。"),
                    F("MinimumOrderValue", "The minimum order value of the supplier.", "供应商的最低订单金额。"),
                    F("OurCodeByYou", "The code used by the supplier for us.", "供应商用于标识我方的代码。"),
                    F("PayViaId", "The pay-via supplier of the supplier.", "供应商的付款途径供应商。"),
                    F("PersonalNumber", "The personal number of a private supplier.", "私人供应商的个人身份证号。"),
                    F("Priority", "The priority of the supplier.", "供应商的优先级。"),
                    F("ReceivingInspecionFromDate", "The start of the receiving-inspection period.", "收货检验期间的开始。"),
                    F("ReceivingInspecionEndDate", "The end of the receiving-inspection period.", "收货检验期间的结束。"),
                    F("StatusId", "The status of the supplier.", "供应商的状态。"),
                    F("TinNumber", "The TIN number of the supplier.", "供应商的 TIN 税号。"),
                    F("ToleranceForEarlyDelivery", "The tolerance for early delivery.", "提前交货的容差。"),
                    F("ToleranceForLateDelivery", "The tolerance for late delivery.", "延迟交货的容差。"),
                    F("UseReferenceNumber", "Whether the supplier uses a reference number.", "供应商是否使用参考号。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.SetSupplierBlockedStatus",
                "Set the blocked status of a supplier.",
                "设置供应商的封锁状态。",
                ["set supplier blocked status", "block supplier", "unblock supplier"], ["设置供应商封锁状态", "封锁供应商"],
                fields: [
                    F("SupplierId", "The supplier to set the blocked status for.", "要设置封锁状态的供应商。"),
                    F("BlockedStatus", "The blocked status (none, message, blocked).", "封锁状态（无、消息、封锁）。"),
                    F("BusinessContactBlockContext", "The context in which the supplier is blocked (register, report, invoices, payments).", "供应商被封锁的上下文（登记、上报、发票、付款）。"),
                    F("Comment", "A comment on the blocking.", "封锁的备注。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.UpdateBankAccountAddressSupplier",
                "Update the address of a supplier bank account.",
                "更新供应商银行账户的地址。",
                ["update bank account address"], ["更新银行账户地址"],
                fields: [
                    F("BankAccountId", "The bank account to update.", "要更新的银行账户。"),
                    F("Addressee", "The addressee of the address.", "地址的收件人。"),
                    F("Field1", "The first address line.", "地址第一行。"),
                    F("Field2", "The second address line.", "地址第二行。"),
                    F("Field3", "The third address line.", "地址第三行。"),
                    F("Field4", "The fourth address line.", "地址第四行。"),
                    F("Field5", "The fifth address line.", "地址第五行。"),
                    F("Locality", "The locality (city) of the address.", "地址的所在地（城市）。"),
                    F("Region", "The region of the address.", "地址的地区。"),
                    F("PostalCode", "The postal code of the address.", "地址的邮政编码。"),
                    F("PostalCodeId", "The postal code record of the address.", "地址的邮政编码记录。"),
                    F("FormReportTranslationGroupId", "The form-report translation group of the address.", "地址的表单报告翻译组。"),
                    F("LanguageId", "The language of the address.", "地址的语言。"),
                    F("SetAddressCountry", "Sets the country of the address together with its format.", "连同格式一起设置地址的国家。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.UpdateBankAccountSupplier",
                "Update a supplier bank account.",
                "更新供应商银行账户。",
                ["update supplier bank account", "update bank account"], ["更新供应商银行账户", "更新银行账户"],
                fields: [
                    F("BankAccountId", "The bank account to update.", "要更新的银行账户。"),
                    F("Number", "The bank account number.", "银行账号。"),
                    F("Type", "The bank account format (IBAN, BBAN, UPIC, miscellaneous).", "银行账户格式（IBAN、BBAN、UPIC 或其他）。"),
                    F("CurrencyId", "The currency of the bank account.", "银行账户的货币。"),
                    F("CountryId", "The country of the bank account.", "银行账户的国家。"),
                    F("IsDefault", "Whether the bank account is the supplier's default.", "银行账户是否为供应商的默认账户。"),
                    F("BankIdentifierCode", "The bank identifier code (BIC/SWIFT).", "银行识别代码（BIC/SWIFT）。"),
                    F("ClearingNumber", "The clearing number of the bank account.", "银行账户的清算号。"),
                    F("ClearingSystem", "The clearing system of the bank account.", "银行账户的清算系统。"),
                    F("CentralBankCodeId", "The central bank code of the bank.", "银行的中央银行代码。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.UpdateCommunicationAddressSupplier",
                "Update a communication address on a supplier.",
                "更新供应商上的通信地址。",
                ["update supplier address", "update communication address"], ["更新供应商地址", "更新通信地址"],
                fields: [
                    F("CommunicationAddressId", "The communication address to update.", "要更新的通信地址。"),
                    F("Type", "The communication channel (phone, fax, e-mail, cell phone).", "通信渠道（电话、传真、电子邮件、手机）。"),
                    F("CommunicationAddressValue", "The communication address value.", "通信地址值。"),
                    F("RecipientOf", "The document types this address receives.", "该地址接收的单据类型。"),
                    F("Remarks", "Remarks on the communication address.", "通信地址的备注。"),
                    F("ContactName", "The contact name of the address.", "地址的联系人姓名。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.UpdateOtherSupplierNumber",
                "Update an additional number of a supplier.",
                "更新供应商的其他编号。",
                ["update other supplier number"], ["更新供应商其他编号"],
                fields: [
                    F("OtherSupplierNumberId", "The other supplier number to update.", "要更新的其他编号。"),
                    F("Number", "The additional number.", "附加编号。"),
                    F("IsDefault", "Whether the number is the supplier's default.", "编号是否为供应商的默认编号。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.UpdateSupplierDeliveryAddress",
                "Update a supplier delivery address.",
                "更新供应商交货地址。",
                ["update supplier delivery address", "update delivery address"], ["更新供应商交货地址", "更新交货地址"],
                fields: [
                    F("SupplierId", "The supplier of the delivery address.", "交货地址所属的供应商。"),
                    F("DeliveryAddressId", "The delivery address to update; defaults to the active one.", "要更新的交货地址；默认为活动的交货地址。"),
                    F("SetAsDefault", "Whether to set the address as the supplier's default.", "是否将该地址设为供应商的默认地址。"),
                    F("WarehouseId", "The warehouse the delivery settings apply to.", "交货设置适用的仓库。"),
                    F("DeliveryMethodId", "The delivery method of the delivery address.", "交货地址的交货方式。"),
                    F("DeliveryTermId", "The delivery term of the delivery address.", "交货地址的交货条款。"),
                    F("VatRateId", "The default VAT rate of the delivery address.", "交货地址的默认增值税率。"),
                    F("VatGroupId", "The VAT group of the delivery address.", "交货地址的增值税组。"),
                    F("ConsigneeReferenceId", "The consignee reference (person) of the delivery address.", "交货地址的收货人联系人。"),
                    F("ConsigneeReferenceName", "The name of the consignee reference.", "收货人联系人的姓名。"),
                    F("Destination", "The destination of the delivery.", "交货的目的地。"),
                    F("DestinationForDeliveryTerm", "The destination used for the delivery term.", "交货条款使用的地点。"),
                    F("DeliveryInstruction", "Delivery instructions for the address.", "该地址的交货说明。"),
                    F("DeliveryWeekdays", "The weekdays on which deliveries are made.", "进行交货的工作日。"),
                    F("TransportTime", "The transport time in days.", "运输时间（天）。"),
                    F("CustomerAccountGroupId", "The customer account group for the delivery address.", "交货地址的客户科目组。"),
                    F("SupplierAccountGroupId", "The supplier account group for the delivery address.", "交货地址的供应商科目组。"),
                    F("Addressee", "The addressee of the address.", "地址的收件人。"),
                    F("Field1", "The first address line.", "地址第一行。"),
                    F("Field2", "The second address line.", "地址第二行。"),
                    F("Field3", "The third address line.", "地址第三行。"),
                    F("Field4", "The fourth address line.", "地址第四行。"),
                    F("Field5", "The fifth address line.", "地址第五行。"),
                    F("Locality", "The locality (city) of the address.", "地址的所在地（城市）。"),
                    F("Region", "The region of the address.", "地址的地区。"),
                    F("PostalCode", "The postal code of the address.", "地址的邮政编码。"),
                    F("LanguageId", "The language of the address.", "地址的语言。"),
                    F("FormReportTranslationGroupId", "The form-report translation group of the address.", "地址的表单报告翻译组。"),
                    F("SetAddressCountry", "Sets the country of the address together with its format.", "连同格式一起设置地址的国家。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.UpdateSupplierMailingAddress",
                "Update the mailing address of a supplier.",
                "更新供应商的邮寄地址。",
                ["update supplier mailing address", "update mailing address"], ["更新供应商邮寄地址", "更新邮寄地址"],
                fields: [
                    F("SupplierId", "The supplier to update.", "要更新的供应商。"),
                    F("Addressee", "The addressee of the address.", "地址的收件人。"),
                    F("Field1", "The first address line.", "地址第一行。"),
                    F("Field2", "The second address line.", "地址第二行。"),
                    F("Field3", "The third address line.", "地址第三行。"),
                    F("Field4", "The fourth address line.", "地址第四行。"),
                    F("Field5", "The fifth address line.", "地址第五行。"),
                    F("Locality", "The locality (city) of the address.", "地址的所在地（城市）。"),
                    F("Region", "The region of the address.", "地址的地区。"),
                    F("PostalCode", "The postal code of the address.", "地址的邮政编码。"),
                    F("FormReportTranslationGroupId", "The form-report translation group of the address.", "地址的表单报告翻译组。"),
                    F("LanguageId", "The language of the address.", "地址的语言。"),
                    F("SetAddressCountry", "Sets the country of the address together with its format.", "连同格式一起设置地址的国家。"),
                ]),
            Content(
                "Monitor.API.Purchase.Commands.Suppliers.UpdateSupplierReference",
                "Update a reference of a supplier.",
                "更新供应商的联系人。",
                ["update supplier reference", "update reference"], ["更新供应商联系人", "更新联系人"],
                fields: [
                    F("SupplierId", "The supplier of the reference.", "联系人所属的供应商。"),
                    F("ReferenceId", "The reference to update.", "要更新的联系人。"),
                    F("Name", "The name of the reference.", "联系人的姓名。"),
                    F("Category", "The category of the reference.", "联系人的类别。"),
                    F("Note", "A note on the reference.", "联系人的备注。"),
                    F("PhoneNumber", "The phone number of the reference.", "联系人的电话号码。"),
                    F("CellPhoneNumber", "The cell phone number of the reference.", "联系人的手机号码。"),
                    F("EmailAddress", "The e-mail address of the reference.", "联系人的电子邮件地址。"),
                    F("FaxNumber", "The fax number of the reference.", "联系人的传真号码。"),
                    F("Comment", "A comment on the reference.", "联系人的备注。"),
                ]),

            // ---- UndoArrivalReporting ------------------------------------------------
            Content(
                "Monitor.API.Purchase.Commands.UndoArrivalReporting.UndoArrivalForRow",
                "Undo the arrival reporting for a purchase-order delivery row.",
                "撤销采购订单交货行的到货上报。",
                ["undo arrival", "cancel arrival reporting"], ["撤销到货上报", "取消到货"],
                fields: [
                    F("PurchaseOrderDeliveryRowId", "The delivery row to undo the arrival for.", "要撤销到货的交货行。"),
                ]),
        ];
    }
}
